[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn next build"
publish = ".next"

[build.environment]
TZ='America/Chicago'

[functions]
  node_bundler = "esbuild"
  

[dev]
  targetPort = 3000

[context.branch-name.dev]
  REBUILD_URL = "https://api.netlify.com/build_hooks/62e445dffcc184007f690d77"